FTechXpress/Models/Product.cs
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace FTechXpress.Models
{
    public class Product
    {
        public int ID { get; set; }
        [Required(ErrorMessage ="Name Required")]
        [MinLength (3,ErrorMessage ="Name Should be more than 3 char")]
       
        public string Name { get; set; }
        [Required(ErrorMessage = "Description Required")]
        [MinLength(10,ErrorMessage = "Name Should be more than 10 char")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Price Required")]
        [Range(1, 9999999, ErrorMessage = "Stock Should be between 1 and 9999999")]
        public Decimal Price { get; set; }
        [Range(1, 500, ErrorMessage = "Stock Should be between 1 and 500")]
        public int Stock { get; set; }
        [Required(ErrorMessage = "Category Required")]
        public virtual Category Category { get; set; } = new Category();
        public virtual List<Cart>? InCart { get; set; }=new List<Cart>();
        public virtual List<Order>? InOrder { get; set; } = new List<Order>();
        public virtual List<WishList?> InWishList { get; set; }=new List<WishList?>();
        public virtual List<Review?> Reviews { get; set; } = new List<Review?>();
    }
}

FTechXpress/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;

namespace FTechXpress.Controllers
{
    public class CartController : Controller
    {
      public IActionResult Add()
        {
          //  HttpContext.Session.SetString("cart", "Added");
         Response.Cookies.Append("cart", "Added to cart");
            return Content("Product added to cart");
        }
    }
}

FTechXpress/Controllers/ProductController.cs
using FTechXpress.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FTechXpress.Controllers
{
    public class ProductController : Controller
    {
        TechXpressContextcs context = new TechXpressContextcs();
       public IActionResult All()
        {
            // This action method will return a view that displays all products.
            var prd = context.Products.Include(p => p.Category).ToList();
            //viewbag is used to pass data from the controller to the view 
            //var usr = context.Users.ToList();
            //ViewBag.user = usr;
            ViewBag.WishList = HttpContext.Session.GetString("wishList");
            ViewBag.Cart = Request.Cookies["cart"];
            return View(prd);
        }
       
        public IActionResult Details(int id)
        {
            // This action method will return a view that displays the details of a specific product.
            var prd = context.Products.Include(P=>P.Category).FirstOrDefault(p => p.ID == id);
            if (prd == null)
            {
                return NotFound();
            }
            return View(prd);
           
        }
       
        public IActionResult New ()
        {
            // This action method will return a view that displays a form for adding a new product.
           
          
            ViewBag.category = context.Categories.ToList();
            return View(new Product());
        }
        [HttpPost]
       
        public IActionResult SaveNew(Product prd)
        {
            var CAT = context.Categories.FirstOrDefault(c => c.ID == prd.Category.ID);
            prd.Category = CAT;
            // This action method will handle the form submission for adding a new product.
            if (ModelState.IsValid)
            {
                context.Products.Add(prd);
                context.SaveChanges();
                TempData["Added"] = "Product Added Successfully";
                return RedirectToAction("All");
            }
            //Product prd = new Product()
            //{ Name = Name, Description = Description, Price = Price, Stock = stock };   
            //context.Products.Add(prd);
            //context.SaveChanges();
            //return RedirectToAction("All");
            ViewBag.category = context.Categories.ToList();
            return View("New", new Product());
        }
      
        public IActionResult Delete(int id)
        {
            // This action method will delete a product and redirect to the All action.
            var prd = context.Products.FirstOrDefault(p => p.ID == id);
            if (prd != null)
            {
                context.Products.Remove(prd);
                context.SaveChanges();
                TempData["Deleted"] = "Product Deleted Successfully";
                return RedirectToAction("All");

            }
            return RedirectToAction("All");
        }
      
        public IActionResult Edit(int id)
        {
            // This action method will return a view that displays a form for editing an existing product.
          var prd = context.Products.Include(prd => prd.Category).FirstOrDefault(p => p.ID == id);
            ViewBag.Category = context.Categories.ToList();
            return View(prd);
        }
        [HttpPost]
      
        public IActionResult SaveEdit(Product prd)
        {
            var old = context.Products.Include(P=>P.Category).FirstOrDefault(p => p.ID == prd.ID);
            if (ModelState.IsValid)
            {
                    old.Name = prd.Name;
                    old.Description = prd.Description;
                    old.Price = prd.Price;
                    old.Stock = prd.Stock;
                    old.Category = prd.Category;
                context.Products.Update(old);
                    context.SaveChanges();
                    TempData["Edited"] = "Product Edited Successfully";
                     return RedirectToAction("All");
            }

            ViewBag.Category = context.Categories.ToList();
            return View("Edit", prd);
           
        }


    }
}

FTechXpress/Controllers/WishlListController.cs
using Microsoft.AspNetCore.Mvc;

namespace FTechXpress.Controllers
{
    public class WishlListController : Controller
    {
        public IActionResult Add()
        {
            // Logic to add an item to the wish list
            HttpContext.Session.SetString("wishList", "Added To WishList");
            return Content("Add To Wish List");
        }
    }
}

FTechXpress/Views/Product/All.cshtml
@model List<Product>

<h1> All Products </h1>
@*  <a type="button" class="btn btn-primary" href="/Product/New">Add New Product</a> *@
<a asp-controller="Product" asp-action="New"  class="btn btn-primary">Add New Product</a>
 <h2>@ViewBag.WishList</h2>
<h2>@ViewBag.Cart</h2>
<h2>@TempData["Deleted"]</h2>
<h2>@TempData["Added"]</h2>
<h2>@TempData["Edited"]</h2>
<!-- Section-->
<section class="py-5">
<div class="container px-4 px-lg-5 mt-5">
	<div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
		
	@foreach (var product in Model)
		{
<div class="col mb-5">
	<div class="card h-100">
		<!-- Product image-->
						<img class="card-img-top" src="~/@product.ID-pro-gold-1662912120.jpg" alt="..." />
		<!-- Product details-->
		<div class="card-body p-4">
			<div class="text-center">
				<!-- Product name-->
				<h5 class="fw-bolder">@product.Name</h5>
				<!-- Product price-->
				@product.Price
			</div>
		</div>
		<!-- Product actions-->
		<div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
			<div class="text-center">
				<a asp-controller="Product" asp-action="Details" asp-route-ID="@product.ID" class="btn btn-outline-success">Details</a>
				<a asp-controller="Product" asp-action="Edit" asp-route-ID="@product.ID" class="btn btn-outline-warning">Edit</a>
				<a asp-controller="product" asp-action="Delete" asp-route-ID="@product.ID" class="btn btn-outline-danger">Delete</a>
			    <a asp-controller="Cart" asp-action="Add" class="btn btn-success mt-4" >To Cart</a>
				<a asp-controller="WishlList" asp-action="Add" class="btn btn-success mt-4">Wish List</a>
			</div>
		</div>
	</div>
</div>
}
		</div>
	</div>
	</section>

FTechXpress/Views/Product/Details.cshtml
@model Product

@* <h1>Product Details</h1> *@
@* 
<h1>@Model.ID</h1>
<h1>@Model.Name</h1>
<h1>@Model.Description</h1>
<h1>@Model.Price</h1>
<h1>@Model.Category.Name</h1> *@

<br />
<a asp-controller="Product" asp-action="All" class="btn btn-outline-dark flex-shrink-0 mt-3">Back to All Products</a>

<!-- Product section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="~/@Model.ID-pro-gold-1662912120.jpg" alt="..." /></div>
            <div class="col-md-6">
                <div class="small mb-1">ID: @Model.ID</div>
                <h1 class="display-5 fw-bolder">@Model.Name</h1>
                <div class="fs-5 mb-5">
                    <span >@Model.Price LE</span>
                   
                </div>
                <p class="lead">@Model.Description</p>
                <div class="d-flex">
                    <form method="post" asp-controller="Cart" asp-action="Add">
                    <input  class="form-control text-center me-3 mt-3" id="inputQuantity" type="num" value="1" style="max-width: 3rem" />
                    <button  class="btn btn-outline-dark flex-shrink-0 mt-3"   type="submit">
                        <i class="bi-cart-fill me-1"></i>
                        Add to cart
                    </button>
                  </form>
                </div>
            </div>
        </div>
    </div>
</section>



<br />

@* <a asp-controller="Cart" asp-action="Add" class="btn btn-success"> To Cart </a> *@

FTechXpress/Views/Product/Edit.cshtml
@model Product 
@{
    SelectList Categories = new SelectList(ViewBag.Category, "ID", "Name");
}
<h1>Editing Product </h1>
<br />
<form method="post" asp-controller="Product" asp-action="SaveEdit" asp-route-ID="@Model.ID">
  <div>
    <label asp-for="Name">Product Name:</label>
    <input asp-for="Name" value="@Model.Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
<br />
<div>
    <label asp-for="Description">Description:</label>
    <input asp-for="Description" value="@Model.Description" />
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
<br />
<div>
        <label asp-for="Price">Price:</label>
        <input asp-for="Price" value="@Model.Price" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
<br />
<div>
        <label asp-for="Stock">Stock:</label>
        <input asp-for="Stock" value="@Model.Stock" />
        <span asp-validation-for="Stock" class="text-danger"></span>
    </div>
<br />
    <div>
        <label asp-for="Category.ID">Category:  </label>
        <select asp-for="Category.ID" asp-items="Categories" value=@Model.Category.Name>
           
        </select>
        <span asp-validation-for="Category" class="text-danger"></span>
    </div>
    <br />
<div>
    <input type="submit" value="Save" />
</div>
</form>

FTechXpress/Views/Product/New.cshtml
@model Product
@{
    SelectList Category = new SelectList(ViewBag.category, "ID", "Name");
}

<h1>Adding New Product</h1>
<br />
<form method="post" asp-controller="Product" asp-action="SaveNew">
	<div>
		<label asp-for="Name"  > Product Name:  </label>
		<input asp-for="Name"	/>
		<span asp-validation-for="Name" class="text-danger"></span>	
	</div>
	<br />
	<div>
		<label asp-for="Description"> Description:  </label>
		<input asp-for="Description" />
		<span asp-validation-for="Description" class="text-danger"></span>
	</div>
	<br />
	<div>
		<label asp-for="Price">Price:  </label>
		<input asp-for="Price" />
		<span asp-validation-for="Price" class="text-danger"></span>
	</div>
	<br />
	<div>
		<label asp-for="Stock">Stock:  </label>
		<input asp-for="Stock" />
		<span asp-validation-for="Stock" class="text-danger"></span>
	</div>
	<br />
	<div>
		<label asp-for="Category.ID">Category:  </label>
		<select asp-for="Category.ID" asp-items="Category">
			<option value="0">Select Category</option>
		</select>
		<span asp-validation-for="Category" class="text-danger"></span>
		

	@* 	<label for="category.ID">Category:  </label>
		<select name="category.ID">
		   <option value="0">Select Category</option> 
            @foreach (var category in Model)
            {
                <option value="@category.ID">@category.Name</option>
            }
			</select> *@
	</div>
	<br />
	<div>
		<input type="submit" value="Add" />
	</div>

</form>